services:
  backend:
    image: aihealth03/viva_backend:latest
    container_name: viva_backend
    ports:
      - "8000:8000"
    env_file:
      - .env.development
    restart: always

volumes:
  mysql_data: